#ifndef HFR_ADVANCED_H
#define HFR_ADVANCED_H

#include "hfr_core.h"
#include "hfr_motion.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ??????????????????????????????????????????????????????????????????????
 * Hierarchical Motion Estimation (Pyramid-based)
 * ??????????????????????????????????????????????????????????????????????
 *
 * Multi-resolution motion estimation improves both speed and accuracy:
 * 1. Build Gaussian pyramids of both frames
 * 2. Estimate motion at coarsest level
 * 3. Propagate and refine estimates to finer levels
 *
 * This reduces the effective search range needed at full resolution
 * and handles large displacements more robustly.
 */

typedef struct {
    double **levels;
    int *widths;
    int *heights;
    int num_levels;
    int original_width;
    int original_height;
} hfr_pyramid_t;

/**
 * @brief Build a Gaussian pyramid from a frame.
 *
 * Each level is half the resolution of the previous level,
 * generated by 5-tap Gaussian filtering and subsampling.
 *
 * Complexity: O(W?H?log(min(W,H))).
 *
 * @param frame    Input frame data (grayscale, W*H).
 * @param width    Frame width.
 * @param height   Frame height.
 * @param levels   Number of pyramid levels.
 * @return         Allocated pyramid (caller must free with hfr_pyramid_free).
 */
hfr_pyramid_t *hfr_pyramid_build(const double *frame, int width, int height, int levels);

/**
 * @brief Free a Gaussian pyramid.
 *
 * @param pyr  Pyramid to free.
 */
void hfr_pyramid_free(hfr_pyramid_t *pyr);

/**
 * @brief Get a specific pyramid level as a flat array.
 *
 * @param pyr    Pyramid.
 * @param level  Level index (0 = finest/original).
 * @return       Pointer to level data (W[level]*H[level] doubles).
 */
const double *hfr_pyramid_get_level(const hfr_pyramid_t *pyr, int level);

/**
 * @brief Hierarchical block matching motion estimation.
 *
 * Estimates motion at coarse levels and refines at finer levels.
 * This is the standard approach for production-quality motion estimation.
 *
 * @param prev_frame  Previous frame (grayscale, W*H).
 * @param curr_frame  Current frame (grayscale, W*H).
 * @param width       Frame width.
 * @param height      Frame height.
 * @param config      Motion estimation config (pyramid_levels used).
 * @return            Motion field at full resolution.
 */
hfr_motion_field_t *hfr_me_hierarchical(const double *prev_frame, const double *curr_frame,
                                         int width, int height,
                                         const hfr_motion_est_config_t *config);

/* ??????????????????????????????????????????????????????????????????????
 * Temporal Super-Resolution (Multi-Frame Fusion)
 * ??????????????????????????????????????????????????????????????????????
 *
 * Combines multiple low-resolution or noisy frames to produce a
 * higher-quality output, leveraging sub-pixel motion.
 */

/**
 * @brief Multi-frame temporal fusion with motion compensation.
 *
 * Aligns and averages multiple frames using motion vectors to reduce
 * noise and enhance detail. This is the computational core of
 * both temporal denoising and super-resolution.
 *
 * @param buffer     Frame buffer containing N consecutive frames.
 * @param field      Motion field for each adjacent pair (N-1 fields).
 * @param num_fields Number of motion fields.
 * @param output     Output fused frame (W*H, caller-allocated).
 */
void hfr_temporal_fusion(const hfr_frame_buffer_t *buffer,
                         const hfr_motion_field_t **fields, int num_fields,
                         hfr_frame_t *output);

/**
 * @brief Frame rate-aware deinterlacing with motion compensation.
 *
 * Combines fields from multiple frames for better deinterlacing quality,
 * especially suitable for HFR content where temporal redundancy is high.
 *
 * @param buffer       Frame buffer with at least 3 frames.
 * @param target_frame Index of the frame to deinterlace.
 * @param output        Output progressive frame.
 * @return             0 on success.
 */
int hfr_deinterlace_mocomp(const hfr_frame_buffer_t *buffer, int target_frame,
                           hfr_frame_t *output);

/* ??????????????????????????????????????????????????????????????????????
 * Temporal Artifact Detection
 * ??????????????????????????????????????????????????????????????????????
 */

typedef struct {
    double judder_score;
    double flicker_score;
    double ghosting_score;
    double overall_artifact_score;
    int judder_regions;
    int flicker_regions;
    int ghosting_regions;
} hfr_artifact_report_t;

/**
 * @brief Detect temporal artifacts in a frame sequence.
 *
 * Analyzes frame-to-frame differences to detect:
 * - Judder: irregular motion from mismatched frame rates
 * - Flicker: high-frequency luminance variations
 * - Ghosting: double-exposure from poor interpolation
 *
 * @param buffer  Frame buffer with at least 4 frames.
 * @param report  Output artifact report.
 */
void hfr_detect_artifacts(const hfr_frame_buffer_t *buffer, hfr_artifact_report_t *report);

/* ??????????????????????????????????????????????????????????????????????
 * Frame Rate Adaptive Shutter Simulation
 * ??????????????????????????????????????????????????????????????????????
 */

/**
 * @brief Synthesize motion blur for a given frame rate conversion.
 *
 * When converting 24fps to 60fps, the original 180-degree shutter
 * (1/48s exposure) may look unnatural. This function simulates
 * the appropriate motion blur for the target frame rate.
 *
 * @param src             Source frame (sharp, no motion blur).
 * @param motion_field    Motion vectors.
 * @param src_fps         Source frame rate.
 * @param dst_fps         Destination frame rate.
 * @param shutter_angle   Target shutter angle in degrees.
 * @param dst             Output frame with synthesized motion blur.
 */
void hfr_synthesize_motion_blur(const hfr_frame_t *src,
                                const hfr_motion_field_t *motion_field,
                                double src_fps, double dst_fps,
                                double shutter_angle, hfr_frame_t *dst);

#ifdef __cplusplus
}
#endif

#endif /* HFR_ADVANCED_H */
